#.travis.yml

language: node_js
cache: yarn
node_js:
  - "6.9"

branches:
  only:
    - develop

before_script:
  - yarn global add firebase-tools
  - yarn global add @angular/cli

script:
  - yarn build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive

notifications:
  email:
    on_failure: change
    on_success: change